### ISSUE TITLE
Endpoint to change the password

### ISSUE THREAD

**Issue by konrab-ima** [colingit93/AP0Backend#40] opened 2021-04-21 08:31 UTC
I need your opinion here.
We have 3 options to do that:
- we simply use the "update profile" functionality (which would mean, you could close this ticket)
- we reuse the endpoint for "reset forgotten password" (which would mean, the user has go through the same process)
- there is a separate endpoint (e.g. users/change-password) which we will simply pass "password1" and "password2" in the body.
All of the above would be fine by me.

**Comment by GZEI** [comment] 2021-04-21 08:33
possible duplicate of #13 ?

**Closed** 2021-04-28 17:18 UTC
